# Generated by Django 2.2.4 on 2019-08-09 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_greeting_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='greetingitem',
            name='parent_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Greeting'),
        ),
    ]
